### ISSUE TITLE
how does it work?

### ISSUE THREAD

**Issue by kocierik** [elie-chaaban/react-native-maps-alternatives-directions#1]
It still works? I tried it but I found no difference from the original. could you tell me how to test it for my application?

**Comment by elie-chaaban** [comment]
It does, just add your api Key and the routes if there are more than one, you would get them in the array

**Comment by kocierik** [comment]
thank you, now work!

**Comment by kocierik** [comment]
Just one last question, what does the `preferredRoute` field mean?

**Comment by elie-chaaban** [comment]
It s just what route I want to get its coordinates,

I think you should always pass it to get the alternative routes as I remember.

For example if you pass it 1, and there is already more than one route available, you would get the coordinates of the second route

**Comment by kocierik** [comment]
thank you!
